dist: xenial
language: node_js
node_js: node
services: docker
cache:
  npm: true
  directories:
    - .nyc_output

env:
  global:
    - ARANGODB_VERSION=3.4
    - PATH=$HOME/.local/bin:$PATH
    - CACHE_NAME=GLOBAL
  matrix:
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/routes/document/*.js"]' NYC_OUT=mmfiles-integration-document
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-query GREP='Path as query param'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-body GREP='Path as body param'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/routes/document/*.js"]' NYC_OUT=rocksdb-integration-document
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-query GREP='Path as query param'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-body GREP='Path as body param'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/handlers/createHandlers.js", "test/unit/lib/handlers/removeHandlers.js", "test/unit/lib/handlers/replaceHandlers.js", "test/unit/lib/handlers/updateHandlers.js", "test/unit/lib/middleware/*.js"]' NYC_OUT=mmfiles-unit-lib-rest
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.js"]' NYC_OUT=mmfiles-unit-lib-handlers-log-query GREP='Path as query param'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.js"]' NYC_OUT=mmfiles-unit-lib-handlers-log-body GREP='Path as body param'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-rest
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-log-db GREP='Log - DB Scope'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-log-graph GREP='Log - Graph Scope'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-log-coll GREP='Log - Collection Scope'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-log-ng GREP='Log - Node Glob Scope'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-lib-operations-log-nb GREP='Log - Node Brace Scope'
    - ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/diff/*.js"]' NYC_OUT=mmfiles-unit-lib-operations-diff
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/handlers/createHandlers.js", "test/unit/lib/handlers/removeHandlers.js", "test/unit/lib/handlers/replaceHandlers.js", "test/unit/lib/handlers/updateHandlers.js", "test/unit/lib/middleware/*.js"]' NYC_OUT=rocksdb-unit-lib-rest
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.js"]' NYC_OUT=rocksdb-unit-lib-handlers-log-query GREP='Path as query param'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.js"]' NYC_OUT=rocksdb-unit-lib-handlers-log-body GREP='Path as body param'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-rest
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-log-db GREP='Log - DB Scope'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-log-graph GREP='Log - Graph Scope'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-log-coll GREP='Log - Collection Scope'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-log-ng GREP='Log - Node Glob Scope'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-lib-operations-log-nb GREP='Log - Node Brace Scope'
    - ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/diff/*.js"]' NYC_OUT=rocksdb-unit-lib-operations-diff

install:
  - npm install

before_script:
  - rm -rf ./.nyc_output/*
  - npx nyc instrument . ./.nyc_output/instrumented
  - cp -r ./.nyc_output/instrumented/lib .
  - docker pull arangodb:$ARANGODB_VERSION
  - docker run
    -e ARANGO_RANDOM_ROOT_PASSWORD=1
    -e ARANGO_STORAGE_ENGINE=$ARANGO_STORAGE_ENGINE
    -e EVTEST_FILES="$EVTEST_FILES"
    -e NYC_OUT=$NYC_OUT
    -e GREP="$GREP"
    -v "$PWD":/mnt/evstore
    -d --name arangodb arangodb:$ARANGODB_VERSION
  - export ARANGO_ROOT_PASSWORD=$(docker logs arangodb |grep 'GENERATED ROOT PASSWORD' |awk '{ print $4 }')
  - sleep 30
  - docker exec -i arangodb arangosh --server.password=$ARANGO_ROOT_PASSWORD < ./test/travis/create_db.js
  - docker exec arangodb /mnt/evstore/test/travis/install.sh

script: travis_wait 60 docker exec arangodb /mnt/evstore/test/travis/run.sh

before_cache: rm -rf ./.nyc_output/instrumented

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a140dc8d21490c900ab
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - stage: analysis

      git:
        depth: false

      addons:
        sonarcloud:
          organization: "adityamukho-github"

      install:
        - npm install

      before_script:
        - npx nyc merge ./.nyc_output ./.nyc_output/out.json
        - npx nyc report --report-dir=./test/reports -r lcovonly
        - npx eslint ./main.js ./lib/ ./scripts
          -f json
          -o ./test/reports/eslint-report.json
      script:
        - npx nyc check-coverage --lines 80 --functions 80 --branches 70
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] || [ "$TRAVIS_PULL_REQUEST_SLUG" = "$TRAVIS_REPO_SLUG" ]; then
            sonar-scanner;
          fi'
