dist: xenial
language: node_js
node_js: node
services: docker
cache:
  npm: true
branches:
  except:
    - documentation

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
  matrix:
    #mmfiles v3.4
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=mmfiles-integration-show
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=mmfiles-integration-rest
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-rest
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-operations-log
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=mmfiles-unit-rest

    #rocksdb v3.4
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=rocksdb-integration-show
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=rocksdb-integration-rest
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-rest
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-operations-log
    - ARANGODB_VERSION=3.4 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=rocksdb-unit-rest

    #mmfiles v3.5
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=mmfiles-integration-show
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=mmfiles-integration-rest
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-rest
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-operations-log
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=mmfiles-unit-rest

    #rocksdb v3.5
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=rocksdb-integration-show
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=rocksdb-integration-rest
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-rest
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-operations-log
    - ARANGODB_VERSION=3.5 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=rocksdb-unit-rest

    #mmfiles v3.6
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=mmfiles-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=mmfiles-integration-show
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=mmfiles-integration-rest
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=mmfiles-unit-handlers-rest
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=mmfiles-unit-operations-log
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=mmfiles EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=mmfiles-unit-rest

    #rocksdb v3.6
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/event/log.test.js"]' NYC_OUT=rocksdb-integration-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/history/show.test.js"]' NYC_OUT=rocksdb-integration-show
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/integration/lib/routes/document/*.js", "test/integration/lib/routes/event/diff.test.js", "test/integration/lib/routes/history/filter.test.js", "test/integration/lib/routes/history/traverse.test.js"]' NYC_OUT=rocksdb-integration-rest
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-query GREP='Path as query param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/logHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-log-body GREP='Path as body param'
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/handlers/createHandlers.test.js", "test/unit/lib/handlers/removeHandlers.test.js", "test/unit/lib/handlers/replaceHandlers.test.js", "test/unit/lib/handlers/updateHandlers.test.js", "test/unit/lib/handlers/diffHandlers.test.js", "test/unit/lib/handlers/showHandlers.test.js", "test/unit/lib/handlers/filterHandlers.test.js", "test/unit/lib/handlers/traverseHandlers.test.js"]' NYC_OUT=rocksdb-unit-handlers-rest
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/operations/log/index.test.js"]' NYC_OUT=rocksdb-unit-operations-log
    - ARANGODB_VERSION=3.6 ARANGO_STORAGE_ENGINE=rocksdb EVTEST_FILES='["test/unit/lib/*.js", "test/unit/lib/middleware/*.js", "test/unit/lib/operations/*.js", "test/unit/lib/operations/commit/*.js", "test/unit/lib/operations/diff/*.js", "test/unit/lib/operations/show/*.js", "test/unit/lib/operations/filter/*.js", "test/unit/lib/operations/traverse/*.js", "test/unit/lib/operations/log/helpers.test.js"]' NYC_OUT=rocksdb-unit-rest

install:
  - npm install
  - pip install --user awscli

before_script:
  - aws configure set aws_access_key_id "$AWS_ACCESS_KEY"
  - aws configure set aws_secret_access_key "$AWS_SECRET_KEY"
  - aws configure set region us-east-1
  - rm -rf ./.nyc_output/*
  - npx nyc instrument . ./.nyc_output/instrumented
  - cp -r ./.nyc_output/instrumented/lib .
  - docker pull arangodb:$ARANGODB_VERSION
  - docker run
    -e ARANGO_RANDOM_ROOT_PASSWORD=1
    -e ARANGO_STORAGE_ENGINE=$ARANGO_STORAGE_ENGINE
    -e EVTEST_FILES="$EVTEST_FILES"
    -e NYC_OUT=$NYC_OUT
    -e GREP="$GREP"
    -e TRAVIS_JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    -v "$PWD":/mnt/evstore
    -d --name arangodb arangodb:$ARANGODB_VERSION
  - export ARANGO_ROOT_PASSWORD=$(docker logs arangodb |grep 'GENERATED ROOT PASSWORD' |awk '{ print $4 }')
  - sleep 60
  - docker exec -i arangodb arangosh --server.password=$ARANGO_ROOT_PASSWORD < ./test/travis/create_db.js
  - docker exec arangodb /mnt/evstore/test/travis/install.sh

script: ./test/travis/travis-runner.sh

after_script:
  - aws s3 sync ./test/reports/ s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER/
  - echo "Copied test reports to s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER"

after_success:
  - rm -rf ./.nyc_output/instrumented
  - aws s3 sync ./.nyc_output/ s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER/
  - echo "Copied coverage data to s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER"

#before_cache: rm -rf ./.nyc_output/instrumented

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2a140dc8d21490c900ab
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - stage: analysis

      git:
        depth: false

      addons:
        sonarcloud:
          organization: "adityamukho-github"

      install:
        - npm install
        - pip install --user awscli

      before_script:
        - aws configure set aws_access_key_id "$AWS_ACCESS_KEY"
        - aws configure set aws_secret_access_key "$AWS_SECRET_KEY"
        - aws configure set region us-east-1
        - aws s3 sync s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER/ ./.nyc_output/ --exclude '*' --include 'coverage*.json'
        - echo 'Found following files in ./.nyc_output/:'
        - ls -l ./.nyc_output
        - npx nyc merge ./.nyc_output ./.nyc_output/out.json
        - npx nyc report --report-dir=./test/reports -r lcovonly
        - npx eslint ./main.js ./lib/ ./scripts
          -f json
          -o ./test/reports/eslint-report.json
      script:
        - npx nyc check-coverage --lines 80 --functions 80 --branches 70
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] || [ "$TRAVIS_PULL_REQUEST_SLUG" = "$TRAVIS_REPO_SLUG" ]; then
            sonar-scanner;
          fi'
      after_script:
        - aws s3 sync ./test/reports/ s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER/
        - echo "Copied coverage and lint reports to s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER"
        - aws s3 cp ./.nyc_output/out.json s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER/
        - echo "Copied merged coverage data to s3://$TRAVIS_S3_BUCKET/$TRAVIS_BUILD_NUMBER"
